package isemenov.ide.plugin.vcs.ui;

import isemenov.ide.plugin.PluginUI;
import isemenov.ide.plugin.vcs.FileVCSStatus;
import isemenov.ide.plugin.vcs.VCSIntegrationPlugin;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.util.Optional;

public class VCSPluginUI implements PluginUI {
    private final VCSIntegrationPlugin integrationPlugin;

    private JPanel mainPanel;
    private JList<FileVCSStatus> fileList;
    private JButton refreshButton;
    private JButton commitButton;
    private JButton updateButton;

    public VCSPluginUI(VCSIntegrationPlugin integrationPlugin) {
        this.integrationPlugin = integrationPlugin;

        refreshButton.addActionListener(e -> refreshTrackedFiles());
        commitButton.addActionListener(e -> commitTrackedFiles());
        updateButton.addActionListener(e -> updateAllFiles());

        fileList.setModel(integrationPlugin.getTrackedFileStatusesList());
        //So that it is selected via right click too
        fileList.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    JList list = (JList) e.getSource();
                    int row = list.locationToIndex(e.getPoint());
                    list.setSelectedIndex(row);
                }
            }
        });

        VCSFileListItemPopupMenu listItemPopupMenu =
                new VCSFileListItemPopupMenu(e -> deleteSelectedFile(),
                                             e -> revertSelectedFile(),
                                             e -> refreshSelectedFile());

        fileList.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
                maybeShowPopup(e);
            }

            public void mouseReleased(MouseEvent e) {
                maybeShowPopup(e);
            }

            private void maybeShowPopup(MouseEvent e) {
                if (e.isPopupTrigger()) {
                    if (fileList.getSelectedIndex() >= 0)
                        listItemPopupMenu.filePopup();
                    else
                        listItemPopupMenu.nonFilePopup();
                    listItemPopupMenu.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private void refreshTrackedFiles() {
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.refreshTrackedFileStatuses();
                return null;
            }
        }.execute();
    }

    private void commitTrackedFiles() {
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.commitTrackedFiles();
                return null;
            }
        }.execute();
    }

    private void updateAllFiles() {
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.updateProject();
                return null;
            }
        }.execute();
    }

    private void deleteSelectedFile() {
        FileVCSStatus file = fileList.getSelectedValue();
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.removeFile(file.getFile());
                integrationPlugin.refreshFileStatus(file.getFile());
                return null;
            }
        }.execute();
    }

    private void revertSelectedFile() {
        FileVCSStatus file = fileList.getSelectedValue();
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.revertFileChanges(file.getFile());
                integrationPlugin.refreshFileStatus(file.getFile());
                return null;
            }
        }.execute();
    }

    private void refreshSelectedFile() {
        FileVCSStatus file = fileList.getSelectedValue();
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                integrationPlugin.refreshFileStatus(file.getFile());
                return null;
            }
        }.execute();
    }

    @Override
    public Optional<WindowFocusListener> getWindowFocusListener() {
        return Optional.of(new WindowFocusListener() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
                refreshTrackedFiles();
            }

            @Override
            public void windowLostFocus(WindowEvent e) {

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        toolBar1.setOrientation(1);
        toolBar1.setRollover(true);
        toolBar1.putClientProperty("JToolBar.isRollover", Boolean.TRUE);
        mainPanel.add(toolBar1, BorderLayout.WEST);
        refreshButton = new JButton();
        refreshButton.setFocusable(false);
        refreshButton.setIcon(new ImageIcon(getClass().getResource("/icons/refresh-button.png")));
        refreshButton.setText("");
        refreshButton.setToolTipText("Refresh");
        toolBar1.add(refreshButton);
        commitButton = new JButton();
        commitButton.setIcon(new ImageIcon(getClass().getResource("/icons/upload-button.png")));
        commitButton.setText("");
        toolBar1.add(commitButton);
        updateButton = new JButton();
        updateButton.setIcon(new ImageIcon(getClass().getResource("/icons/download-button.png")));
        updateButton.setText("");
        toolBar1.add(updateButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(0, 0));
        mainPanel.add(scrollPane1, BorderLayout.CENTER);
        fileList = new JList();
        fileList.setSelectionMode(0);
        scrollPane1.setViewportView(fileList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
