package isemenov.ide.ui.component;

import javax.swing.*;
import java.awt.*;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;

public class LoadingDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JLabel loadingLabel;

    private SwingWorker<String, Void> worker;

    public LoadingDialog(String title, Callable<String> operation) {
        setTitle(title);
        setModal(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonOK);
        buttonOK.addActionListener(e -> onOK());
        buttonOK.setVisible(false);
        pack();
        setResizable(false);

        worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() throws Exception {
                return operation.call();
            }

            @Override
            protected void done() {
                try {
                    setLoadingComplete(get());
                } catch (InterruptedException e) {
                    //Won't happen
                } catch (ExecutionException e) {
                    dispose();
                    JOptionPane.showMessageDialog(null,
                                                  e.getMessage(),
                                                  "Error!",
                                                  JOptionPane.ERROR_MESSAGE);
                }
            }
        };
    }

    public void execute() {
        worker.execute();
        setVisible(true);
    }

    private void setLoadingComplete(String message) {
        loadingLabel.setIcon(null);
        loadingLabel.setText(message);
        buttonOK.setVisible(true);
        contentPane.revalidate();
        pack();
    }

    private void onOK() {
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.NORTH);
        loadingLabel = new JLabel();
        loadingLabel.setHorizontalAlignment(0);
        loadingLabel.setIcon(new ImageIcon(getClass().getResource("/icons/loading.gif")));
        loadingLabel.setText("");
        panel1.add(loadingLabel, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        contentPane.add(panel2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3);
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel3.add(buttonOK, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
